# ---------------------------------------------------------
# 
# Rosetta Configuration
#
# See https://gitlab.com/knowledge-integration/ciim/rosetta/-/wikis/Build,%20Development%20and%20Deployment/Configuration
# for available configuration options.
#
# Note that further settings may be required to allow for other mappings etc.';
# always check before over-writing a live file with this one 
#
# ---------------------------------------------------------


# Added from Richard Light's Proteus implementation:
base_paths:
  proteus: ../config/proteus
  
server:
  # You can change the port that Rosetta runs on here
  # 4923 is the default
  # Staging uses 4923
  # RL was using 24920
  port: 4923 

logging:
  pattern:
    level: "%5p %X{CorrelationId}"
  level: 
    root: warn
    org.elasticsearch.client: error
    com.k_int.rosetta: info # RL had TRACE
    com.k_int.rosetta.iiif.presentation.v3: trace
    # Added from Richard Light's Proteus implementation:
    com.k_int.proteus: TRACE

management:
  endpoints:
    web:
      exposure:
        include:
          - health

spring:
  graphql:
    path: /api/graphql

springdoc:
  api-docs:
    path: /spec
    

rosetta:
  # Added from Richard Light's Proteus implementation:
  view:
    # A "view" is essentially a REST endpoint that is highly configurable.
    views:
      - name: json-formats
      # You can customize the path and path parameters here. Path segments enclosed in {} define the path parameters' positions/names:
        paths:
          - /json/{ID}
          - /json/{datatype}/{ID}
        # The choice of profile affects what data is available and what transforms are applied to each record:
        profile: search
        methods:
          - GET
        transforms:
          response:
            policy: list
            # You can control the response model by altering the Proteus spec for these glyphs:
            names:
              - to-simple-data-response
              - view-response
              - json-transforms
          # The same syntax applies to a 'request' block, where you can control the request model by altering the Proteus spec for the glyphs specified in 'names'.
          
      - name: xml-formats
        paths:
          - /xml/{ID}
          - /xml/{datatype}/{ID}
        profile: search
        methods:
          - GET
        transforms:
          response:
            policy: list
            names:
              - to-simple-data-response
              - view-response
              - xml-transforms
        media_type: application/xml

      - name: help-formats
        paths:
          - /help/{ID}
        profile: search
        methods:
          - GET
        transforms:
          response:
            policy: list
            names:
              - to-simple-data-response
              - view-response
              - help-transforms
        media_type: application/html

  cache:
    enabled: true
    manager: 
      enabled: false
      
  # Added from Richard Light's Proteus implementation:
  profile:
    profiles:
      - name: search
        providers:
          policy: list
          names:
            - elasticsearch
        transforms:
          request:
            - glyphs:
                policy: list
                names:
                  - view-request
                  
      - name: iiif
        providers:
           policy: list
           names: 
             - elasticsearch
        transforms:
          request:
            - glyphs:
                policy: list
                names:
                  - extract-id
                  - elastic-generic-search
          data: 
            - glyphs:
                policy: list
                names:
                  - iiif-proteus
  plugins:
    iiif:
       baseUrl: http://localhost:4923/
       mediaArtifact: mid # This can be changed to "zoom" or other artifacts
       externalMediaBaseUrl: http://localhost/mediaLib/
       IIIFMediaBaseUrl: http://localhost:8182/iiif/3/
       manifestKey:
         keyType: IDENTIFIER
         identifierType: pid
       externalMediaKey:
         keyType: ARTIFACT_LOCATION
       IIIFMediaKey:
         keyType: IDENTIFIER
         identifierType: pid
    # RL values:
    # iiif:
      # profile: iiif
      # base_url: https://staging-data.ng.ac.uk
      # exclude_api_path: true
      # manifest_key:
        # key_type: IDENTIFIER
        # identifier_type: PID
      # identifier_query_string: identifier.__pid
      # IIIF_media_base_url: ${rosetta.plugins.iiif.base_url}/media/iiif/
      # external_media_base_url: ${rosetta.plugins.iiif.base_url}/media/static/   

    # Added from Richard Light's Proteus implementation:
    proteus:
      api:
        http_client: ok_http
        enable_file_read: true
      
      # Type repositories are the new way to manage custom types without the need to declare each individual include file.
      # Instead you define one base path per repository and Proteus will automatically discover any types defined within the file tree.
      # The form each file within a repository should take depends on its "shape", as described below.
      # By default, repositories are mutable, so you don't need to restart Rosetta to update/add/remove types.
      repository:
        repositories:
          - name: dublin-core
            type: file
            properties:
              path: ${base_paths.proteus}/dublin-core
              # Repositories of shape "map" expect a top-level map of custom type definitions (i.e. the contents of "type_registry" in a regular include file)
              shape: map
          - name: linked-art
            type: file
            properties:
              path: ${base_paths.proteus}/linked-art
              shape: map
          - name: jskos
            type: file
            properties:
              path: ${base_paths.proteus}/jskos
              shape: map
          - name: skos
            type: file
            properties:
              path: ${base_paths.proteus}/skos
              shape: map
          - name: lido
            type: file
            properties:
              path: ${base_paths.proteus}/lido
              shape: map
          - name: utils
            type: file
            properties:
              path: ${base_paths.proteus}/utils
              shape: map
              # Repositories of shape "root" treat each file as the full type definition for the specific type given by its base file name.
              # E.g. if the file path is "./linked_art/repository/types/my_custom_type.json", then its type will be "my_custom_type"

  provider:
    globalTimeoutMillis: 60000
    timeoutMillis: 60000
    providers:
      - name: elasticsearch
        type: elasticsearch
        domainConverter: es-converter
        properties:
          host: localhost
          index: ciim # This can be changed to "public", "internal-sensitive" etc. to point at ES publication endpoints
          port: 19200

  # RL values for remote access to staging:
  # provider:
    # timeout: 1m
    # global_timeout: 1m
    # providers:
      # - name: elasticsearch
        # type: elasticsearch
        # properties:
          # host: staging-data.ng.ac.uk
          # protocol: https
          # path_prefix: /es/
          # port: 443
          # index: public
          # skip_ping: true
  
  domain:
    converters:
      - name: es-converter
        type: elastic-default

  transform:
    timeoutMillis: 60000 # RL had: timeout: 1m
    glyphs:
      - name: jolt-iiif-metadata
        type: jolt
        properties:
          specPath: D:/CIIM/config/rosetta/jolt-iiif-metadata-spec.json
          mutable: true

      # All the following added from Richard Light's Proteus implementation:
      # System
      - name: to-generic-search
        type: to-generic-search

      - name: to-simple-data-response
        type: to-simple-data-response
        
      - name: elastic-generic-search
        type: elastic-generic-search
        properties:
          search_config:
            id_fields: 
              - field: '@admin.uid'
            
      - name: view-request
        type: proteus
        properties:
          mutable: true
          # Edit this file to change how requests are handled:
          spec: ${base_paths.proteus}/view-request.json
          
      - name: view-response
        type: proteus
        properties:
          mutable: true
          # Edit this file to control the final output of the response:
          spec: ${base_paths.proteus}/view-response.json
              
      - name: xml-transforms
        type: proteus
        input: full
        properties:
          mutable: true
          # This is the main XML transform and simple invokes your various dc, lido and skos custom types
          spec: ${base_paths.proteus}/xml-transforms.json
          repositories:
            policy: list
            names:
              - dublin-core
              - skos
              - lido
              - utils
          config:
            properties:
              # Base for URLs generated within this end-point:
              xml_base_url: https://data.ng.ac.uk/
              # This configures the Elasticsearch base url used in the "linked_record_entity_type" custom type
              # N.b. update value as required:
              es_base_url: https://staging-data.ng.ac.uk/es/public/_search?
              local_base_url: http://localhost:24920/json/
              
      - name: json-transforms
        type: proteus
        input: full
        properties:
          mutable: true
          spec: ${base_paths.proteus}/json-transforms.json
          repositories:
            policy: list
            names:
              - linked-art
              - jskos
              - utils
          config:
            properties:
              # Base for URLs generated within this end-point:
              linked_art_base_url: https://data.ng.ac.uk/ 
              # This configures the Elasticsearch base url used in the "linked_record_entity_type" custom type
              # N.b. update value as required:
              es_base_url: https://staging-data.ng.ac.uk/es/public/_search?
              local_base_url: http://localhost:24920/json/

      - name: help-transforms
        type: proteus
        input: full
        properties:
          mutable: true
          spec: ${base_paths.proteus}/help-transforms.json
          repositories:
            policy: list
            names:
              - dublin-core
              - linked-art
              - skos
              - jskos
              - lido
              - utils
          config:
            properties:
              local_base_url: http://localhost:24920/json/
                  
      - name: iiif-proteus
        type: proteus
        properties:
          mutable: true
          spec: ${base_paths.proteus}/iiif/iiif.json
          include:
            - ${base_paths.proteus}/iiif/iiif-include.json
          config:
            properties:
              base_url:
                presentation: ${rosetta.plugins.iiif.base_url}
                image: ${rosetta.plugins.iiif.IIIF_media_base_url}
                media: ${rosetta.plugins.iiif.external_media_base_url}               
                
      - name: extract-id
        type: proteus
        properties:
          mutable: true
          spec: ${base_paths.proteus}/iiif/extract-id.json