# Rosetta Configuration
#
# See https://gitlab.com/knowledge-integration/ciim/rosetta/-/wikis/Build,%20Development%20and%20Deployment/Configuration
# for available configuration options.
base_paths:
  proteus: ../config/proteus
  
server:
  port: 24920

logging:
  level: 
    com.k_int.rosetta: TRACE
    com.k_int.proteus: TRACE

rosetta:
  view:
    views:
      - name: json-formats
        paths:
          - /json/{ID}
          - /json/{datatype}/{ID}
        profile: search
        methods:
          - GET
        transforms:
          response:
            policy: list
            names:
              - to-simple-data-response
              - view-response
              - json-transforms
              
      - name: xml-formats
        paths:
          - /xml/{ID}
          - /xml/{datatype}/{ID}
        profile: search
        methods:
          - GET
        transforms:
          response:
            policy: list
            names:
              - to-simple-data-response
              - view-response
              - xml-transforms
        media_type: application/xml

  cache:
    enabled: true
    manager: 
      enabled: false
      
  profile:
    profiles:
      - name: search
        providers:
          policy: list
          names:
            - elasticsearch
        transforms:
          request:
            - glyphs:
                policy: list
                names:
                  - view-request            
                  
      - name: iiif
        providers:
           policy: list
           names: 
             - elasticsearch
        transforms:
          request:
            - glyphs:
                policy: list
                names:
                  - extract-id
                  - elastic-generic-search
          data: 
            - glyphs:
                policy: list
                names:
                  - iiif-proteus
  plugins:
    iiif:
      profile: iiif
      base_url: https://staging-data.ng.ac.uk
      exclude_api_path: true
      manifest_key:
        key_type: IDENTIFIER
        identifier_type: PID
      identifier_query_string: identifier.__pid
      IIIF_media_base_url: ${rosetta.plugins.iiif.base_url}/media/iiif/
      external_media_base_url: ${rosetta.plugins.iiif.base_url}/media/static/   
    proteus:
      api:
        http_client: ok_http
        enable_file_read: true
      
      repository:
        repositories:
          - name: dublin-core
            type: file
            properties:
              path: ${base_paths.proteus}/dublin-core
              shape: root
          - name: linked-art
            type: file
            properties:
              path: ${base_paths.proteus}/linked-art
              shape: map
          - name: jskos
            type: file
            properties:
              path: ${base_paths.proteus}/jskos
              shape: map
          - name: skos
            type: file
            properties:
              path: ${base_paths.proteus}/skos
              shape: map
          - name: utils
            type: file
            properties:
              path: ${base_paths.proteus}/utils
              shape: map

  provider:
    timeout: 1m
    global_timeout: 1m
    providers:
      - name: elasticsearch
        type: elasticsearch
        properties:
          host: staging-data.ng.ac.uk
          protocol: https
          path_prefix: /es/
          port: 443
          index: public
          skip_ping: true
  
  transform:
    timeout: 1m
    glyphs:
      - name: to-generic-search
        type: to-generic-search

      - name: to-simple-data-response
        type: to-simple-data-response
        
      - name: elastic-generic-search
        type: elastic-generic-search
        properties:
          search_config:
            id_fields: 
              - field: '@admin.uid'
            
      - name: view-request
        type: proteus
        properties:
          mutable: true
          spec: ${base_paths.proteus}/view-request.json
          
      - name: view-response
        type: proteus
        properties:
          mutable: true
          spec: ${base_paths.proteus}/view-response.json
              
      - name: xml-transforms
        type: proteus
        input: full
        properties:
          mutable: true
          spec: ${base_paths.proteus}/xml-transforms.json
          repositories:
            policy: list
            names:
              - dublin-core
              - skos
              - utils
          config:
            properties:
              xml_base_url: https://staging-data.ng.ac.uk/rosetta3/temp/xml/ # Base for URLs generated within this end-point  
              es_base_url: https://staging-data.ng.ac.uk/es/public/_search?
              
      - name: json-transforms
        type: proteus
        input: full
        properties:
          mutable: true
          spec: ${base_paths.proteus}/json-transforms.json
          repositories:
            policy: list
            names:
              - linked-art
              - jskos
              - utils
          config:
            properties:
              linked_art_base_url: https://staging-data.ng.ac.uk/rosetta3/temp/json/ # Base for URLs generated within this end-point  
              es_base_url: https://staging-data.ng.ac.uk/es/public/_search?
                
                  
      - name: iiif-proteus
        type: proteus
        properties:
          mutable: true
          spec: ${base_paths.proteus}/iiif/iiif.json
          include:
            - ${base_paths.proteus}/iiif/iiif-include.json
          config:
            properties:
              base_url:
                presentation: ${rosetta.plugins.iiif.base_url}
                image: ${rosetta.plugins.iiif.IIIF_media_base_url}
                media: ${rosetta.plugins.iiif.external_media_base_url}               
                
      - name: extract-id
        type: proteus
        properties:
          mutable: true
          spec: ${base_paths.proteus}/iiif/extract-id.json